### ISSUE TITLE
3/15 → D/YY

### ISSUE THREAD

**Issue by rnp716** [gr2m/moment-parseformat#17]
`moment.parseFormat('3/15')` parsed to `D/YY`, I expected: `M/D`

Although D/YY is a valid interpretation, it's not the most intuitive one.

**Comment by gr2m** [comment]
That's a tough one. It could as well be `M/YY`. Can't think of any arguments in favor of the one or the other at the moment, but `D/YY` definitely doesn't make any sense.

**Comment by onecreative** [comment]
I was going to say it should default to M/YY, simply because that's what goes on a credit card. But then I realized that credit card expires don't need to be interpreted or reformatted, and if you take them out of the equation most scenarios probably would be M/DD (birthdays and upcoming events), followed by M/YY.

**Comment by rnp716** [comment]
Maybe special case it with a comment in the source that the assigned format string literal might be changed depending on the programmer's imagined use cases? In my situation, I was just testing out the functionality with birthdays, but I could imagine another programmer going the other way.

On the whole, that seems like a good solution for any ambiguous parsing.

**Comment by zoepage** [comment]
So, basically it should be `D/MM` or `M/YY` right? Because `D/YY` really doesn't make sense here.
How should we handle this @gr2m ?

**Comment by gr2m** [comment]
I'd suggest the following:

1. if the last number is > 12, then we do Month/Year
2. If the first number is > 12, then we do Day/Month
3. If both is > 12, then ... somethings wrong
4. If both is < 12, then default to Month/Year

**Comment by zoepage** [comment]
I agree with you except here: 
> If both is < 12, then default to Month/Year

I think, this would be a great idea for Day/Month, because this use case is much more common.
As far as we use Month/Year primary for things like e.g. exp. dates on credit cards, last number should be > 12 anyways.

**Comment by gr2m** [comment]
Okay, yeah, I don't mind, we should just document it. Maybe let's add an "Special Cases" section in the README?

In theory, "month/day" would also be possible, but I'd say lets ignore this until someone brings it up with a real use case :)

**Comment by zoepage** [comment]
Sounds great. 
Will do. Thanks :)

**Comment by zoepage** [comment]
fixed with #32

**Comment by gr2m** [comment]
please don't close until PR is merged
