### ISSUE TITLE
February 6th, 2014 9.20 → MMMM Do, YYYY D.YY

### ISSUE THREAD

**Issue by gr2m** [gr2m/moment-parseformat#19]
`moment.parseFormat('February 6th, 2014 9.20')` parsed to `MMMM Do, YYYY D.YY`, I expected: `MMMM Do, YYYY H:mm`

**Comment by zoepage** [comment]
The dot in `9.20` is causing the bug here. 

As far as `9:20` is a standard format, question here would be... Are we setting the format as a default or do we allow the `9.20` format, if we also have a day, month and year?

(Just want to make sure to make the right decision here :) )

**Comment by gr2m** [comment]
I think Ideally we would be able to handle the `.` in a smart way, so that if we already found a Month, let's parse remaning two numbers separated by either `:` or `.` as hours & minutes

**Comment by zoepage** [comment]
fixed with #33

**Comment by gr2m** [comment]
fyi I've rebased on gh-pages and `git push -f`d it for simpler review

**Comment by zoepage** [comment]
merged via 0e57f8438d8607a23f1a72c3576bfc27c6d1dacd
