### ISSUE TITLE
dependency on moment version

### ISSUE THREAD

**Issue by mwymann** [gr2m/moment-parseformat#27]
Hello

Is there a reason why your bower packages dependencies refers to moment version 2.5.1?

kind regards

**Comment by gr2m** [comment]
No, not really. in package.json we also depend on some specific git revision. Want to see if all tests still work with latest moment, and send a PR?

**Comment by zoepage** [comment]
Updated npm version (for package) and static version loaded from cdn for demo index.html to 2.10.6
and all tests are green. :)

Will be deployed after https://github.com/gr2m/moment.parseFormat/pull/30 is merged.

**Comment by zoepage** [comment]
#30 is merged. :)
