### ISSUE TITLE
Library cannot be minified

### ISSUE THREAD

**Issue by moses-seeq** [gr2m/moment-parseformat#35]
This library cannot be minified and concatenated with the rest of our dependencies, but when delivered unminified all works well.

**Comment by gr2m** [comment]
what do you use to minify? Can you try to minify this version: https://wzrd.in/standalone/moment-parseformat

**Comment by moses-seeq** [comment]
Unfortunately, I've not had any luck with this version either.  We use usemin to minify.  I thought at first that it might be caused by the lack of semi-colons, but that change alone has not resolved the problem either.  Thanks for looking into it.

**Comment by gr2m** [comment]
@moses-seeq can you please check that you use latest version of `usemin`? If you are on latest version, can you check what npm package `usemin` is using internally for minification, and what version? Do you see any errors?

I've tested it with latest `uglify-js` version, and had no issues. I've pasted the output in the console on http://momentjs.com/docs/ and `moment.parseFormat` worked without problems.

**Comment by gr2m** [comment]
also, try to add a `;` in the beginning and end:

```
;(function (root, factory) {
...
});
```

**Comment by gr2m** [comment]
can you try again? I've pushed a few updates
https://wzrd.in/standalone/moment-parseformat

**Comment by moses-seeq** [comment]
I'm sorry to have taken so long to get back to you.  I was unsuccessfully attempting to fit this between tasks so I finally created a new task for it.  So far it appears to minify successfully in our environment.  I'm going to run a few more tests, just to be sure.  Is the link above the same as the recently released version?

Thank you!

**Comment by gr2m** [comment]
no worries @moses-seeq, I'm very thankful for the time you invest to report the bug and to help get it fixed :) 

Yes, the link above always links to the latest released version

**Comment by moses-seeq** [comment]
Excellent!  Further testing has all been successful.  Thank you for taking care of this.

**Comment by gr2m** [comment]
:+1:
