### ISSUE TITLE
Parsing fractional seconds

### ISSUE THREAD

**Issue by mgd134** [gr2m/moment-parseformat#36]
Hi,

We really like your library. Thanks for the work. We've noticed that the library doesn't produce the correct output for fractional seconds until the input gets all the way to milliseconds. I have modified the code in my fork so that it will parse tenths and hundredths of a second properly. Would you like me to submit a pull request?

Mike

**Comment by gr2m** [comment]
Hey Mike, sure, pull requests are always more than welcome, thanks for sharing!

**Comment by gr2m** [comment]
done via #37
