### ISSUE TITLE
31/12/2013 → MM/DD/YYYY

### ISSUE THREAD

**Issue by danilotorrisi** [gr2m/moment-parseformat#40]
`moment.parseFormat('31/12/2013')` parsed to `MM/DD/YYYY`, I expected: `DD/MM/YYYY`.

Other test cases:

`moment.parseFormat('12/31/2013')` parsed to `MM/DD/YYYY` => Correct
`moment.parseFormat('31-12-2013')` parsed to `DD-MM-YYYY` => Correct
`moment.parseFormat('12-31-2013')` parsed to `MM-DD-YYYY` => Correct

**Comment by gr2m** [comment]
Good catch! Would you mind sending a PR? I'm happy to walk you through what it takes, if you need any guidance

**Comment by gr2m** [comment]
closed via #40. Released as https://github.com/gr2m/moment-parseformat/releases/tag/v2.0.1
