### ISSUE TITLE
2016-07-20 16:33:58+0000 → YYYY-MM-DD H:mm:ss YYYY

### ISSUE THREAD

**Issue by eburlaka** [gr2m/moment-parseformat#53]
`moment.parseFormat('2016-07-20 16:33:58+0000')` parsed to `YYYY-MM-DD H:mm:ss YYYY`, I expected: `YYYY-MM-DD H:mm:ss+0000`

**Comment by gr2m** [comment]
moment.parseFormat is meant to help parsing dates from user input. `2016-07-20 16:33:58+0000` looks more like a timestamp, you can pass it directly to `new Date('2016-07-20 16:33:58+0000')` or `moment('2016-07-20 16:33:58+0000').format('MMMM Do YYYY, h:mm:ss a')`. Does that work for you?
