### ISSUE TITLE
npm version 2.1.2 doesn't include index.js

### ISSUE THREAD

**Issue by kkirby** [gr2m/moment-parseformat#55]
Just upgraded to the latest version of this module and got a resolution error on it. Apparently the NPM version doesn't have the index.js file included.

**Comment by gr2m** [comment]
ooops sorry checking

**Comment by gr2m** [comment]
ugh you are right, I thought the `"main"` file would always be included, fixing now

**Comment by gr2m** [comment]
Travis is slow right now, but once [this build](https://travis-ci.org/gr2m/moment-parseformat/builds/147242103) finishes, it will release v2.1.3 with the fix. Sorry for that!

**Comment by gr2m** [comment]
[v2.1.3](https://github.com/gr2m/moment-parseformat/releases/tag/v2.1.3) is released and fixes this issue

**Comment by kkirby** [comment]
Thanks! I appreciate the quick turnaround on this.
