### ISSUE TITLE
Incorrect Date Conversion in nodered, moment.js in javascript works fine.

### ISSUE THREAD

**Issue by brmo** [gr2m/moment-parseformat#85]
I posted this on the node-red-contrib-moment github issue board. A awesome contributor pointed me it seems to be an issue with this library.  Here is the issue.

https://github.com/TotallyInformation/node-red-contrib-moment/issues/20

Thanks!

**Comment by gr2m** [comment]
The input value `2018-06-01T18:13:03.909192+00:00 ` as too many decimal points, I’ve never seen that format before. I think this lib can handle up to 3. In your case, I think that would be precise enough? Maybe remove all decimal points after that?

**Comment by brmo** [comment]
I went ahead and did a regex in my node-red flow to capture only the first three, so I would say there is nothing more to do here. Odd that Home Assistant does a second with so much precision.

Thanks anyways!
